In [2]:
import numpy as np


Numpay é uma biblioteca para computação científica  que fornece um objeto array multidimensional, vários objetos derivados (como arrays mascarados e matrizes) e uma variedade de rotinas para operações rápidas em arrays, incluindo matemática, lógica, manipulação de forma, classificação, seleção, E/S. , transformadas discretas de Fourier, álgebra linear básica, operações estatísticas básicas, simulação aleatória e muito mais.

###Array é a estrutura principal da biblioteca numpy;

In [7]:
# Uma array criarda a partir de uma lista

l = [4,8,2,12,5,8,0]

arr = np.array(l)
arr

array([ 4,  8,  2, 12,  5,  8,  0])

In [10]:
#Criando um nympy array do zero

np.zeros((2,2)) #passa-se a dimensâo do array e todos os elementos serão zero


array([[0., 0.],
       [0., 0.]])

In [12]:
arr_range = np.arange(0,11) # valor inicial, valor final e o passo
arr_range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
np.random.random((3,3)) #inicia um array com valores randomicos

array([[0.39651186, 0.24134352, 0.71999303],
       [0.0401617 , 0.28411948, 0.22506811],
       [0.11468961, 0.6886703 , 0.50755645]])

1. Crie um array com 4 linhas e 3 colunas com valores aleatórios

In [14]:
np.random.random((4,3))

array([[0.67599518, 0.82607401, 0.21811206],
       [0.2191673 , 0.62465226, 0.19849127],
       [0.63193194, 0.48599046, 0.59350822],
       [0.15179555, 0.59602644, 0.28818412]])

2. Crie um array com 5 colunas e 10 linhas inicializados com zeros

In [15]:
np.zeros((10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

3. Crie um array com valores inteiros 3 linhas e 5 colunas com valores aleatórios

In [18]:
np.random.randint(10,31, size=(3,5))

array([[30, 10, 27, 15, 29],
       [15, 10, 29, 25, 10],
       [10, 13, 11, 11, 23]])

In [19]:
#array 3D


arr1_2d = np.array ([[1,2],[3,4]])
arr2_2d = np.array ([[5,6],[7,8]])
arr3_2d = np.array ([[9,2],[3,4]])

arr_3d = np.array([arr1_2d, arr2_2d, arr3_2d ])

In [20]:
arr_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]],

       [[9, 2],
        [3, 4]]])

Dimensõees do array (atributos e métodos)

Atributo: .shape

Método: .flatten() - transforma uma matriz em um array de 1 dimensão, ele achata o array.
        .reshape() - ele muda as dimensões da array


In [21]:
arr_3d.shape

(3, 2, 2)

In [24]:
arr_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]],

       [[9, 2],
        [3, 4]]])

In [27]:
arr = np.zeros((3,4,2))

In [28]:
arr.shape

(3, 4, 2)

In [29]:
arr.flatten()

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0.])

In [30]:
arr_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]],

       [[9, 2],
        [3, 4]]])

In [31]:
arr_3d.reshape((4,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [2, 3, 4]])

1. Reduza o array (5,7) a apenas uma dimensão

In [32]:
a57 = np.random.random((5,7))

In [34]:
a1d =a57.flatten()

In [35]:
a1d

array([0.18330109, 0.06412554, 0.27377161, 0.87331566, 0.76099722,
       0.65107405, 0.1243905 , 0.56974139, 0.08065725, 0.53532517,
       0.92560491, 0.23433863, 0.23475932, 0.71710171, 0.44280383,
       0.37999052, 0.12578477, 0.67023821, 0.65112429, 0.01318467,
       0.29821257, 0.58644288, 0.1768097 , 0.62001217, 0.33007368,
       0.60939376, 0.60744102, 0.65421444, 0.42348835, 0.52708818,
       0.16873833, 0.53911567, 0.74358373, 0.47089058, 0.33151237])

2. Considerando que você é uma organizadora de um jogo de bingo. Crie um array que irá representar a cartilha desses jogos de bingo. Os números da sua cartelas variam entre 1 e 30, e você terá 10 participantes. Cada cartela terá 12 números (4,3).
Crie um array que represente esse jogo.

In [37]:
bingo = np.random.randint(1,31, size=(10,4,3))
bingo

array([[[ 5, 14,  8],
        [18, 29, 17],
        [16, 29, 28],
        [22, 14,  8]],

       [[11, 13, 26],
        [26, 20,  7],
        [ 6, 23, 20],
        [23, 28, 29]],

       [[18,  4, 24],
        [10, 27, 15],
        [ 9, 27, 23],
        [26, 14, 19]],

       [[22, 23,  7],
        [22, 21, 22],
        [25, 10, 18],
        [12, 28,  5]],

       [[25, 16, 10],
        [21, 25, 11],
        [11, 12, 16],
        [19, 17, 21]],

       [[ 4, 26,  7],
        [ 7, 28, 23],
        [21, 14, 13],
        [28,  3, 20]],

       [[17, 23, 23],
        [28, 23, 21],
        [13, 10, 22],
        [29, 21, 30]],

       [[21, 23, 29],
        [18, 21, 17],
        [28,  2, 28],
        [ 2,  8, 26]],

       [[ 1,  2,  8],
        [30, 11, 23],
        [10, 24, 27],
        [15, 26, 11]],

       [[11,  6, 16],
        [10,  3, 12],
        [ 4, 30, 23],
        [ 8, 12,  5]]])

3. Faça o reshape das suas cartelas para que haja 5 cartelas de 4 linhas e 6 colunas.

In [38]:
bingo.reshape((5,4,6))

array([[[ 5, 14,  8, 18, 29, 17],
        [16, 29, 28, 22, 14,  8],
        [11, 13, 26, 26, 20,  7],
        [ 6, 23, 20, 23, 28, 29]],

       [[18,  4, 24, 10, 27, 15],
        [ 9, 27, 23, 26, 14, 19],
        [22, 23,  7, 22, 21, 22],
        [25, 10, 18, 12, 28,  5]],

       [[25, 16, 10, 21, 25, 11],
        [11, 12, 16, 19, 17, 21],
        [ 4, 26,  7,  7, 28, 23],
        [21, 14, 13, 28,  3, 20]],

       [[17, 23, 23, 28, 23, 21],
        [13, 10, 22, 29, 21, 30],
        [21, 23, 29, 18, 21, 17],
        [28,  2, 28,  2,  8, 26]],

       [[ 1,  2,  8, 30, 11, 23],
        [10, 24, 27, 15, 26, 11],
        [11,  6, 16, 10,  3, 12],
        [ 4, 30, 23,  8, 12,  5]]])

Tipos de dados em Numpy array

Tipos em Numpy Vs tipo em Python

Python              Numpy
-  int              - np.int64
- Float             - np.int32
                    - np.float64
                    - np.float32
Bits e Bytes
Bits- é a menor unidade de dados de um computador
1 byte é a sequencia de 8 bits.



Atributo .dtype e tipo default

In [40]:
np.array([2.14, 6.25, 160.87, 8.4]).dtype

dtype('float64')

In [42]:
np.array([2, 6 , 160, 8]).dtype

dtype('int32')

In [43]:
#String

np.array(["Hello", "Code", "Girls"]).dtype

dtype('<U5')

Conversão e coersão

In [45]:
#dtype como argumento

arr_float23 = np.array ([2.14, 6.25, 160.87], dtype= np.float32)
arr_float23

array([  2.14,   6.25, 160.87], dtype=float32)

In [50]:
#Conversao

arr_vf = np.array ([[True, False], [True, True]],dtype = np.bool8)
arr_vf.astype(np.int32)

C:\Users\cedma\AppData\Local\Temp\ipykernel_11612\4168051480.py:3: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  arr_vf = np.array ([[True, False], [True, True]],dtype = np.bool8)


array([[1, 0],
       [1, 1]])

In [53]:
#coerção

np.array(["pedra", False, 42, 42.42])

array(['pedra', 'False', '42', '42.42'], dtype='<U32')

Hierarquia de coerção

In [4]:
#Adicionar um float a um array de int mudrá todo os valores para float

np.array([0,10]).dtype

dtype('int32')

In [3]:
np.array([0, 10, 1.]).dtype

dtype('float64')

In [7]:
#Adicionar um inteiro em um array de bloeanos transfomará todo o array em inteiros.

np.array([True, False,12]).dtype


dtype('int32')

Tipos de dados em um numpy array

In [8]:
np.array([5.4, 6.7, 2.1]).dtype

dtype('float64')

In [9]:
np.array([5, 6, 2]).dtype

dtype('int32')

In [13]:
np.array(["hello", "oi", "womakerscod"]).dtype

dtype('<U11')

In [14]:
x = np.array([3, 4, 2.1])

In [15]:
x[1]

4.0

In [17]:
np.array([True, 2, False]).dtype

dtype('int32')

In [20]:
vf = np.array([True, 2, False])

In [21]:
vf.dtype

dtype('int32')

In [23]:
vf.astype(np.bool_)

array([ True,  True, False])

In [19]:
x.astype(np.int32)

array([3, 4, 2])

#Manipulando arrays

In [24]:
arr = np.array([2, 4, 6, 7, 8])
arr[1]

4

In [26]:
cartela_bingo = np.array([[16, 10, 3 ,15],
                          [14, 23, 17, 27],
                          [6, 19, 3, 1],
                          [10, 4 ,18, 19 ]])
cartela_bingo

array([[16, 10,  3, 15],
       [14, 23, 17, 27],
       [ 6, 19,  3,  1],
       [10,  4, 18, 19]])

In [28]:
cartela_bingo[:,1].shape

(4,)

In [29]:
cartela_bingo[:,1].reshape((4,1))

array([[10],
       [23],
       [19],
       [ 4]])

In [30]:
cartela_bingo[0]

array([16, 10,  3, 15])

In [31]:
np.sort(cartela_bingo)

array([[ 3, 10, 15, 16],
       [14, 17, 23, 27],
       [ 1,  3,  6, 19],
       [ 4, 10, 18, 19]])

In [32]:
np.sort(cartela_bingo, axis=0)

array([[ 6,  4,  3,  1],
       [10, 10,  3, 15],
       [14, 19, 17, 19],
       [16, 23, 18, 27]])

In [ ]:
Explorando Ecossistemas:\n",
        "Como bióloga marinha, me encontrei em uma expedição nas profundezas do Oceano Pacífico, onde estávamos estudando a biodiversidade e a saúde dos recifes de coral. O catálogo abaixo demonstra dados das espécies encontradas, considere a seguinte ordem de colunas:\n",
        "\n",
        "**ID da espécie, quantidade de representantes encontrados, profundeza, tamanho médio da espécie**\n",
        "\n",
        "\n",
        "\n",
        "*  Selecione a segunda coluna com a quantidade de espécies encontradas e adicione em um array as qtd_especies.\n",
        "*  De qtd_especies selecione apenas as primeiras 3 quantidades e print\n",
        "*  Print as 5 últimas quantidades de espécies\n",
        "*  Crie um array que contenha apenas os tamanhos das espécies e ordene por ordem crescente\n",

In [34]:
especies = np.array([[747,  89,  33,   5],
                            [623, 123,  32,  13],
                            [501,  22,  49,   2],
                            [116, 101,  42,  10],
                            [297,  56,  69,  22],
                            [613,  64,  27,   7],
                            [295,  84,  29,  14],
                            [692, 105,  72,  16],
                            [229, 103,  35,   5],
                            [374, 124,  70,   1]])
especies

array([[747,  89,  33,   5],
       [623, 123,  32,  13],
       [501,  22,  49,   2],
       [116, 101,  42,  10],
       [297,  56,  69,  22],
       [613,  64,  27,   7],
       [295,  84,  29,  14],
       [692, 105,  72,  16],
       [229, 103,  35,   5],
       [374, 124,  70,   1]])

In [35]:
#Selecione a segunda coluna com a quantidade de espécies encontradas e adicione em um array as qtd_especies

qtd_especies = especies[:,1]
qtd_especies

array([ 89, 123,  22, 101,  56,  64,  84, 105, 103, 124])

In [37]:
# De qtd_especies selecione apenas as primeiras 3 quantidades e print\n"

print(qtd_especies[0:3])

[ 89 123  22]


In [38]:
especies.shape

(10, 4)

In [41]:
print(qtd_especies[-5:])

[ 64  84 105 103 124]


In [42]:
#Crie um array que contenha apenas os tamanhos das espécies e ordene por ordem crescente

np.sort(especies[:,3])

array([ 1,  2,  5,  5,  7, 10, 13, 14, 16, 22])

#Filtrando arrays

Indexação sofisticada (fancy indexing) e máscara (mask) em array 2D

In [44]:
pessoas_id_idade = np.array([[1, 22], [2, 21], [3, 27], [4, 26]])
pessoas_id_idade[:, 1] % 2 ==0

array([ True, False, False,  True])

In [47]:
#praticar

arr1 = np.array([1, 2, 3, 4, 5])
mask = arr1 % 3 == 0
mask

array([False, False,  True, False, False])

In [48]:
pessoas_id_idade = np.array([[1, 22], [2, 21], [3, 27], [4, 26]])
pessoas_id_idade

array([[ 1, 22],
       [ 2, 21],
       [ 3, 27],
       [ 4, 26]])

In [49]:
mask_maior21 = pessoas_id_idade[:,1] > 21
mask_maior21

array([ True, False,  True,  True])

In [50]:
pessoas_id_idade[mask_maior21]

array([[ 1, 22],
       [ 3, 27],
       [ 4, 26]])

In [51]:
np.where(mask_maior21)

(array([0, 2, 3], dtype=int64),)

In [52]:
cartela_bingo = np.array([[16, 10, 3 ,15],
                          [14, 23, 17, 27],
                          [6, 19, 3, 1],
                          [10, 4 ,18, 19 ]])
cartela_bingo

array([[16, 10,  3, 15],
       [14, 23, 17, 27],
       [ 6, 19,  3,  1],
       [10,  4, 18, 19]])

In [53]:
np.where(cartela_bingo % 3 ==0, "div3", cartela_bingo)

array([['16', '10', 'div3', 'div3'],
       ['14', '23', '17', 'div3'],
       ['div3', '19', 'div3', '1'],
       ['10', '4', 'div3', '19']], dtype='<U11')

In [54]:
np.where(pessoas_id_idade >21, "maior idade", pessoas_id_idade)

array([['1', 'maior idade'],
       ['2', '21'],
       ['3', 'maior idade'],
       ['4', 'maior idade']], dtype='<U11')

## 1.2 Ainda usando o Array de espécies marítimas.

*   Usando um index booleano crie um array que contém os dados da maior espécie encontrada (considerando o seu tamanho), esse valor corresponde ao valor 22.
*   Usando fency index faça um array que contém apenas dados da espécie com ID 297
*   Usando np.where() faça um array com a linha com dados correspondentes a espécie com 105 representantes encontrados.
*   Considere a profundeza em que o espécie foi encontrada substitua valores maiores que 60 com \"Profundo\
   

In [55]:
especies = np.array([[747,  89,  33,   5],
                            [623, 123,  32,  13],
                            [501,  22,  49,   2],
                            [116, 101,  42,  10],
                            [297,  56,  69,  22],
                            [613,  64,  27,   7],
                            [295,  84,  29,  14],
                            [692, 105,  72,  16],
                            [229, 103,  35,   5],
                            [374, 124,  70,   1]])
especies

array([[747,  89,  33,   5],
       [623, 123,  32,  13],
       [501,  22,  49,   2],
       [116, 101,  42,  10],
       [297,  56,  69,  22],
       [613,  64,  27,   7],
       [295,  84,  29,  14],
       [692, 105,  72,  16],
       [229, 103,  35,   5],
       [374, 124,  70,   1]])

In [58]:
# Usando um index booleano crie um array que contém os dados da maior espécie encontrada (considerando o seu tamanho), esse valor corresponde ao valor 22.

especies[:,3] ==22

array([False, False, False, False,  True, False, False, False, False,
       False])

In [61]:
maior_especie = especies[especies[:, 3] ==22]
maior_especie

array([[297,  56,  69,  22]])

In [64]:
#Usando fency index faça um array que contém apenas dados da espécie com ID 297

mas_297 = especies[:,0] ==297

In [66]:
especies[mas_297]

array([[297,  56,  69,  22]])

In [67]:
# Usando np.where() faça um array com a linha com dados correspondentes a espécie com 105 representantes encontrados.
 
np.where(especies[:,1] ==105)

(array([7], dtype=int64),)

In [68]:
especies[np.where(especies[:,1] ==105)]

array([[692, 105,  72,  16]])

In [70]:
#Considere a profundeza em que o espécie foi encontrada substitua valores maiores que 60 com \"Profundo\

np.where(especies[:, 2] > 60, "profundo", especies [:, 2])

array(['33', '32', '49', '42', 'profundo', '27', '29', 'profundo', '35',
       'profundo'], dtype='<U11')

#Adicionando e removendo dados do array
 
*Concatenando linhas
*Concatenando colunas

#Calculos com Arrays

Python
* .sum()
* .min()
* .max()
* .mean()
* .cumsum()

In [71]:
cartela_bingo

array([[16, 10,  3, 15],
       [14, 23, 17, 27],
       [ 6, 19,  3,  1],
       [10,  4, 18, 19]])

In [73]:
cartela_bingo1 = cartela_bingo[:3]
cartela_bingo1

array([[16, 10,  3, 15],
       [14, 23, 17, 27],
       [ 6, 19,  3,  1]])

In [75]:
cartela_bingo2 = cartela_bingo[-1:]
cartela_bingo2 

array([[10,  4, 18, 19]])

In [77]:
cartela_bingo == np.concatenate((cartela_bingo1, cartela_bingo2))

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [78]:
sala_espera = np.array([['5', '30', '1', 'Alice'],
                        ['6', '29', '1', 'Bob'],
                         ['7', '35', '3', 'Cristina'],
                          ['8', '34', '3', 'Luiz'] ])
sala_espera

array([['5', '30', '1', 'Alice'],
       ['6', '29', '1', 'Bob'],
       ['7', '35', '3', 'Cristina'],
       ['8', '34', '3', 'Luiz']], dtype='<U8')

In [79]:
np.delete(sala_espera, 3, axis =0)

array([['5', '30', '1', 'Alice'],
       ['6', '29', '1', 'Bob'],
       ['7', '35', '3', 'Cristina']], dtype='<U8')

## 1.3 Ainda no conjunto 'especies'.
      
*   Adicione mais 2 espécies ao array: [[204, 10, 40, 12], [392, 11, 81, 11]]
*   Adicione mais uma coluna na no array original agora com o número de espécies encontradas com que indica se o animal enxerga ou não: [0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0]
    

In [80]:
especies

array([[747,  89,  33,   5],
       [623, 123,  32,  13],
       [501,  22,  49,   2],
       [116, 101,  42,  10],
       [297,  56,  69,  22],
       [613,  64,  27,   7],
       [295,  84,  29,  14],
       [692, 105,  72,  16],
       [229, 103,  35,   5],
       [374, 124,  70,   1]])

In [83]:
novas_especies = np.array([[204, 10, 40, 12], [392, 11, 81, 11]])

In [84]:
np.concatenate((especies, novas_especies))

array([[747,  89,  33,   5],
       [623, 123,  32,  13],
       [501,  22,  49,   2],
       [116, 101,  42,  10],
       [297,  56,  69,  22],
       [613,  64,  27,   7],
       [295,  84,  29,  14],
       [692, 105,  72,  16],
       [229, 103,  35,   5],
       [374, 124,  70,   1],
       [204,  10,  40,  12],
       [392,  11,  81,  11]])

In [85]:
ver = np.array([0, 1, 0, 0, 0, 0, 1, 0, 1, 1]).reshape((10,1))

In [86]:
ver

array([[0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1]])

In [87]:
np.concatenate((especies, ver), axis=1)

array([[747,  89,  33,   5,   0],
       [623, 123,  32,  13,   1],
       [501,  22,  49,   2,   0],
       [116, 101,  42,  10,   0],
       [297,  56,  69,  22,   0],
       [613,  64,  27,   7,   0],
       [295,  84,  29,  14,   1],
       [692, 105,  72,  16,   0],
       [229, 103,  35,   5,   1],
       [374, 124,  70,   1,   1]])

# Operações com vetorização

* Comparação operações - Python vs Numpy \n
*Broadcasting (transmissão)

#Salvando arquivos

In [88]:
#Salvando array

arr2d = np.array([[1,2,3],[4, 5, 6]])
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [89]:
arr3d = np.array([[[1, 2, 3],[4, 5, 6]], [[1, 2, 3],[4, 5, 6]]])

In [90]:
arr3d.shape

(2, 2, 3)

In [92]:
np.savetxt('arr2d.csv', arr2d, delimiter=',')

In [96]:
#não é possível salvar em txt ou csv arrays com mais de duas dimensões.
np.save('arr3d', arr3d)

In [97]:
arr_saved_3d = np.load('arr3d.npy')
arr_saved_3d

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [98]:
arr_saved_3d.shape

(2, 2, 3)