In [5]:
import numpy as np


Numpay é uma biblioteca para computação científica  que fornece um objeto array multidimensional, vários objetos derivados (como arrays mascarados e matrizes) e uma variedade de rotinas para operações rápidas em arrays, incluindo matemática, lógica, manipulação de forma, classificação, seleção, E/S. , transformadas discretas de Fourier, álgebra linear básica, operações estatísticas básicas, simulação aleatória e muito mais.

###Array é a estrutura principal da biblioteca numpy;

In [7]:
# Uma array criarda a partir de uma lista

l = [4,8,2,12,5,8,0]

arr = np.array(l)
arr

array([ 4,  8,  2, 12,  5,  8,  0])

In [10]:
#Criando um nympy array do zero

np.zeros((2,2)) #passa-se a dimensâo do array e todos os elementos serão zero


array([[0., 0.],
       [0., 0.]])

In [12]:
arr_range = np.arange(0,11) # valor inicial, valor final e o passo
arr_range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
np.random.random((3,3)) #inicia um array com valores randomicos

array([[0.39651186, 0.24134352, 0.71999303],
       [0.0401617 , 0.28411948, 0.22506811],
       [0.11468961, 0.6886703 , 0.50755645]])

1. Crie um array com 4 linhas e 3 colunas com valores aleatórios

In [14]:
np.random.random((4,3))

array([[0.67599518, 0.82607401, 0.21811206],
       [0.2191673 , 0.62465226, 0.19849127],
       [0.63193194, 0.48599046, 0.59350822],
       [0.15179555, 0.59602644, 0.28818412]])

2. Crie um array com 5 colunas e 10 linhas inicializados com zeros

In [15]:
np.zeros((10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

3. Crie um array com valores inteiros 3 linhas e 5 colunas com valores aleatórios

In [18]:
np.random.randint(10,31, size=(3,5))

array([[30, 10, 27, 15, 29],
       [15, 10, 29, 25, 10],
       [10, 13, 11, 11, 23]])

In [19]:
#array 3D


arr1_2d = np.array ([[1,2],[3,4]])
arr2_2d = np.array ([[5,6],[7,8]])
arr3_2d = np.array ([[9,2],[3,4]])

arr_3d = np.array([arr1_2d, arr2_2d, arr3_2d ])

In [20]:
arr_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]],

       [[9, 2],
        [3, 4]]])

Dimensõees do array (atributos e métodos)

Atributo: .shape

Método: .flatten() - transforma uma matriz em um array de 1 dimensão, ele achata o array.
        .reshape() - ele muda as dimensões da array


In [21]:
arr_3d.shape

(3, 2, 2)

In [24]:
arr_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]],

       [[9, 2],
        [3, 4]]])

In [27]:
arr = np.zeros((3,4,2))

In [28]:
arr.shape

(3, 4, 2)

In [29]:
arr.flatten()

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0.])

In [30]:
arr_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]],

       [[9, 2],
        [3, 4]]])

In [31]:
arr_3d.reshape((4,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [2, 3, 4]])

1. Reduza o array (5,7) a apenas uma dimensão

In [32]:
a57 = np.random.random((5,7))

In [34]:
a1d =a57.flatten()

In [35]:
a1d

array([0.18330109, 0.06412554, 0.27377161, 0.87331566, 0.76099722,
       0.65107405, 0.1243905 , 0.56974139, 0.08065725, 0.53532517,
       0.92560491, 0.23433863, 0.23475932, 0.71710171, 0.44280383,
       0.37999052, 0.12578477, 0.67023821, 0.65112429, 0.01318467,
       0.29821257, 0.58644288, 0.1768097 , 0.62001217, 0.33007368,
       0.60939376, 0.60744102, 0.65421444, 0.42348835, 0.52708818,
       0.16873833, 0.53911567, 0.74358373, 0.47089058, 0.33151237])

2. Considerando que você é uma organizadora de um jogo de bingo. Crie um array que irá representar a cartilha desses jogos de bingo. Os números da sua cartelas variam entre 1 e 30, e você terá 10 participantes. Cada cartela terá 12 números (4,3).
Crie um array que represente esse jogo.

In [37]:
bingo = np.random.randint(1,31, size=(10,4,3))
bingo

array([[[ 5, 14,  8],
        [18, 29, 17],
        [16, 29, 28],
        [22, 14,  8]],

       [[11, 13, 26],
        [26, 20,  7],
        [ 6, 23, 20],
        [23, 28, 29]],

       [[18,  4, 24],
        [10, 27, 15],
        [ 9, 27, 23],
        [26, 14, 19]],

       [[22, 23,  7],
        [22, 21, 22],
        [25, 10, 18],
        [12, 28,  5]],

       [[25, 16, 10],
        [21, 25, 11],
        [11, 12, 16],
        [19, 17, 21]],

       [[ 4, 26,  7],
        [ 7, 28, 23],
        [21, 14, 13],
        [28,  3, 20]],

       [[17, 23, 23],
        [28, 23, 21],
        [13, 10, 22],
        [29, 21, 30]],

       [[21, 23, 29],
        [18, 21, 17],
        [28,  2, 28],
        [ 2,  8, 26]],

       [[ 1,  2,  8],
        [30, 11, 23],
        [10, 24, 27],
        [15, 26, 11]],

       [[11,  6, 16],
        [10,  3, 12],
        [ 4, 30, 23],
        [ 8, 12,  5]]])

3. Faça o reshape das suas cartelas para que haja 5 cartelas de 4 linhas e 6 colunas.

In [38]:
bingo.reshape((5,4,6))

array([[[ 5, 14,  8, 18, 29, 17],
        [16, 29, 28, 22, 14,  8],
        [11, 13, 26, 26, 20,  7],
        [ 6, 23, 20, 23, 28, 29]],

       [[18,  4, 24, 10, 27, 15],
        [ 9, 27, 23, 26, 14, 19],
        [22, 23,  7, 22, 21, 22],
        [25, 10, 18, 12, 28,  5]],

       [[25, 16, 10, 21, 25, 11],
        [11, 12, 16, 19, 17, 21],
        [ 4, 26,  7,  7, 28, 23],
        [21, 14, 13, 28,  3, 20]],

       [[17, 23, 23, 28, 23, 21],
        [13, 10, 22, 29, 21, 30],
        [21, 23, 29, 18, 21, 17],
        [28,  2, 28,  2,  8, 26]],

       [[ 1,  2,  8, 30, 11, 23],
        [10, 24, 27, 15, 26, 11],
        [11,  6, 16, 10,  3, 12],
        [ 4, 30, 23,  8, 12,  5]]])