In [5]:
import numpy as np


Numpay é uma biblioteca para computação científica  que fornece um objeto array multidimensional, vários objetos derivados (como arrays mascarados e matrizes) e uma variedade de rotinas para operações rápidas em arrays, incluindo matemática, lógica, manipulação de forma, classificação, seleção, E/S. , transformadas discretas de Fourier, álgebra linear básica, operações estatísticas básicas, simulação aleatória e muito mais.

###Array é a estrutura principal da biblioteca numpy;

In [7]:
# Uma array criarda a partir de uma lista

l = [4,8,2,12,5,8,0]

arr = np.array(l)
arr

array([ 4,  8,  2, 12,  5,  8,  0])

In [10]:
#Criando um nympy array do zero

np.zeros((2,2)) #passa-se a dimensâo do array e todos os elementos serão zero


array([[0., 0.],
       [0., 0.]])

In [12]:
arr_range = np.arange(0,11) # valor inicial, valor final e o passo
arr_range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
np.random.random((3,3)) #inicia um array com valores randomicos

array([[0.39651186, 0.24134352, 0.71999303],
       [0.0401617 , 0.28411948, 0.22506811],
       [0.11468961, 0.6886703 , 0.50755645]])